# Generated by Django 5.0 on 2025-12-18 10:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Project code/identifier', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='on_track', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Total project budget', max_digits=15)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('completion_percentage', models.IntegerField(default=0, help_text='Overall completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('spi', models.DecimalField(decimal_places=2, default=1.0, help_text='Schedule Performance Index', max_digits=5)),
                ('cpi', models.DecimalField(decimal_places=2, default=1.0, help_text='Cost Performance Index', max_digits=5)),
                ('project_manager', models.CharField(max_length=255)),
                ('sponsor', models.CharField(blank=True, max_length=255)),
                ('team_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='projects_pr_status_d9e5a3_idx'), models.Index(fields=['start_date', 'planned_end_date'], name='projects_pr_start_d_319b2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('achieved', 'Achieved'), ('missed', 'Missed'), ('at_risk', 'At Risk')], default='pending', max_length=20)),
                ('deliverables', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('qa', 'QA Engineer'), ('designer', 'Designer'), ('analyst', 'Business Analyst'), ('architect', 'Architect'), ('manager', 'Project Manager'), ('other', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('allocation_percentage', models.IntegerField(help_text='Percentage allocated to this project', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('schedule', 'Schedule'), ('budget', 'Budget'), ('resource', 'Resource'), ('technical', 'Technical'), ('scope', 'Scope'), ('external', 'External'), ('quality', 'Quality')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigating', 'Mitigating'), ('closed', 'Closed')], default='open', max_length=20)),
                ('probability', models.IntegerField(help_text='Probability of occurrence (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('impact', models.IntegerField(help_text='Impact if occurs (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mitigation_plan', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('identified_date', models.DateField(default=django.utils.timezone.now)),
                ('target_closure_date', models.DateField(blank=True, null=True)),
                ('actual_closure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
            options={
                'ordering': ['-severity', '-probability'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('assigned_to', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_milestone', models.BooleanField(default=False)),
                ('is_critical_path', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
