# Generated by Django 5.0 on 2025-12-19 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('process', 'Process'), ('people', 'People'), ('communication', 'Communication'), ('scope', 'Scope'), ('quality', 'Quality'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('reported_by', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('reported_date', models.DateField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
                ('completion_percentage', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('spent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('spi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('health_score', models.IntegerField()),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('total_risks', models.IntegerField(default=0)),
                ('high_risks', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['project', 'snapshot_date'], name='projects_pr_project_d119a3_idx')],
                'unique_together': {('project', 'snapshot_date')},
            },
        ),
    ]
